// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serverStreamingProto.proto

package ServerSideStreamingProto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Num                  int32    `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3972158e14766f11, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Response struct {
	Result               int32    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3972158e14766f11, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "ServerSideStreamingProto.Request")
	proto.RegisterType((*Response)(nil), "ServerSideStreamingProto.Response")
}

func init() {
	proto.RegisterFile("serverStreamingProto.proto", fileDescriptor_3972158e14766f11)
}

var fileDescriptor_3972158e14766f11 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x0a, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0xcd, 0xcc, 0x4b, 0x0f, 0x28, 0xca, 0x2f, 0xc9,
	0xd7, 0x2b, 0x00, 0x91, 0x42, 0x12, 0xc1, 0x10, 0xb9, 0xcc, 0x94, 0x54, 0x54, 0x79, 0x25, 0x69,
	0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x01, 0x2e, 0x66, 0xbf, 0xd2, 0x5c,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x10, 0x53, 0x49, 0x89, 0x8b, 0x23, 0x28, 0xb5, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8c, 0x8b, 0x2d, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x04, 0xaa,
	0x00, 0xca, 0x33, 0xca, 0xe4, 0xe2, 0x0d, 0xce, 0xcc, 0x2d, 0xc8, 0x49, 0x05, 0x59, 0x91, 0x99,
	0x9c, 0x2a, 0x14, 0xc1, 0xc5, 0xed, 0x9e, 0x5a, 0xe2, 0x92, 0x59, 0x96, 0x59, 0x9c, 0x5f, 0x54,
	0x2c, 0xa4, 0xa8, 0x87, 0xcb, 0x6e, 0x3d, 0xa8, 0xc5, 0x52, 0x4a, 0xf8, 0x94, 0x40, 0xac, 0x57,
	0x62, 0x30, 0x60, 0x4c, 0x62, 0x03, 0x7b, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x69,
	0x51, 0x3b, 0xea, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SimpleServiceClient is the client API for SimpleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleServiceClient interface {
	GetDivisors(ctx context.Context, in *Request, opts ...grpc.CallOption) (SimpleService_GetDivisorsClient, error)
}

type simpleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleServiceClient(cc grpc.ClientConnInterface) SimpleServiceClient {
	return &simpleServiceClient{cc}
}

func (c *simpleServiceClient) GetDivisors(ctx context.Context, in *Request, opts ...grpc.CallOption) (SimpleService_GetDivisorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SimpleService_serviceDesc.Streams[0], "/ServerSideStreamingProto.SimpleService/GetDivisors", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleServiceGetDivisorsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SimpleService_GetDivisorsClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type simpleServiceGetDivisorsClient struct {
	grpc.ClientStream
}

func (x *simpleServiceGetDivisorsClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimpleServiceServer is the server API for SimpleService service.
type SimpleServiceServer interface {
	GetDivisors(*Request, SimpleService_GetDivisorsServer) error
}

// UnimplementedSimpleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSimpleServiceServer struct {
}

func (*UnimplementedSimpleServiceServer) GetDivisors(req *Request, srv SimpleService_GetDivisorsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDivisors not implemented")
}

func RegisterSimpleServiceServer(s *grpc.Server, srv SimpleServiceServer) {
	s.RegisterService(&_SimpleService_serviceDesc, srv)
}

func _SimpleService_GetDivisors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimpleServiceServer).GetDivisors(m, &simpleServiceGetDivisorsServer{stream})
}

type SimpleService_GetDivisorsServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type simpleServiceGetDivisorsServer struct {
	grpc.ServerStream
}

func (x *simpleServiceGetDivisorsServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _SimpleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ServerSideStreamingProto.SimpleService",
	HandlerType: (*SimpleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDivisors",
			Handler:       _SimpleService_GetDivisors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "serverStreamingProto.proto",
}
